Whatsub/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Whatsub.Repositories;
using Whatsub.Models;

namespace Whatsub.Controllers
{
    public class HomeController : ParentController
    {
        public HomeController() : base() { }
        public HomeController(IRepository<SubtitleProfile> ProfileRepo) : base(ProfileRepo) { }
        //All repos and constructors put in ParentController

        public ActionResult Index()
        {
            IndexViewModel Model = new IndexViewModel();
            // Get newest subtitle
            Model.NewSubtitles = (from P in _ProfileRepo.GetAll()
                                from S in P.Subtitles
                                orderby S.ID descending
                                select new ProfileView {
                                    ID = S.ID,
                                    Title = P.Title,
                                    Year = P.Year
                                }).Take(5).ToList();
            // Get top subtitles
            var TopSubtitles = (from Profile in _ProfileRepo.GetAll()
                                  where Profile.Subtitles.Count() != 0
                                  orderby Profile.Downloads.Count() descending
                                  select Profile).Take(5).ToList();

            Model.TopSubtitles = new List<ProfileView>();
            // add top subtitles to list
            foreach (var Top in TopSubtitles)
            {
                Model.TopSubtitles.Add(new ProfileView 
                { 
                    ID = Top.Subtitles.First().ID, 
                    Title = Top.Title, 
                    Year = Top.Year 
                });
            }

            return View(Model);
        }

        public ActionResult Help()
        {
            ViewBag.Message = "Help page.";
            return View();
        }
        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Whatsub/Controllers/RequestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Whatsub.Repositories;
using Whatsub.Models;
using TMDbLib.Client;
using TMDbLib.Objects.Movies;
using TMDbLib.Objects.General;
using System.Text;
using System.IO;
using System.Text.RegularExpressions;
using Microsoft.AspNet.Identity;

namespace Whatsub.Controllers
{
    public class RequestController : ParentController
    {
        public RequestController() : base() { }
        public RequestController(IRepository<SubtitleProfile> ProfileRepo) : base(ProfileRepo) { }
        public ActionResult Index(int? Page)
        {
            if (!Page.HasValue)
            {
                Page = 1;
            }
            // Get all requests and orders the by upvotes
            var Requests = (from p in _ProfileRepo.GetAll()
                            where p.Requests.Count() != 0
                            from r in p.Requests
                            orderby r.Upvotes.Count() descending
                            select new
                            {
                                ID = r.ID,
                                Title = p.Title,
                                Year = p.Year,
                                Upvotes = r.Upvotes.Count(),
                                MovieDBID = p.MovieDBID,
                                Language = r.Language,
                                TypeID = p.TypeID
                            }).Skip((Page.Value - 1) * 10).Take(10).ToList();

            PageModel<RequestViewModel> Model = new PageModel<RequestViewModel>();
            Model.Profiles = new List<RequestViewModel>();

            Model.Total = (from P in _ProfileRepo.GetAll()
                           where P.Requests.Count != 0
                           select P).Count();
            Model.Pages = (int)Math.Ceiling((double)Model.Total / 10);
            Model.CurrentPage = Page.Value;
            //Adds requests to list
            foreach (var R in Requests)
            {
                // checks if a request has a MovieDBID
                if (R.MovieDBID != null)
                {
                    // if id is 1 add information from moviDB as movie
                    if(R.TypeID == 1)
                    {
                        var Movie = _TMDb.GetMovie(R.MovieDBID.Value);
                        Model.Profiles.Add(new RequestViewModel 
                        { 
                            ID = R.ID, 
                            Title = Movie.Title, 
                            Year = R.Year, 
                            Upvotes = R.Upvotes, 
                            PosterPath = Movie.PosterPath,
                            LanguageName = R.Language.LanguageName,
                            LanguageID = R.Language.ID,
                            LanguageClass = R.Language.LanguageClass,
                            TypeID = R.TypeID
                        });
                    }
                    // id id is 2 add information from movieDB as tvshow
                    else
                    {
                        var TvShow = _TMDb.GetTvShow(R.MovieDBID.Value);
                        Model.Profiles.Add(new RequestViewModel {
                            ID = R.ID,
                            Title = TvShow.Name,
                            Year = R.Year, 
                            Upvotes = R.Upvotes, 
                            PosterPath = TvShow.PosterPath, 
                            LanguageName = R.Language.LanguageName,
                            LanguageID =R.Language.ID,
                            LanguageClass = R.Language.LanguageClass,
                            TypeID = R.TypeID
                        });
                    }
                }
                // Is there is no movie DB info then it will just have information from user
                else
                {
                    Model.Profiles.Add(new RequestViewModel {
                        ID = R.ID,
                        Title = R.Title,
                        Year = R.Year, 
                        Upvotes = R.Upvotes,
                        LanguageName = R.Language.LanguageName, 
                        LanguageClass = R.Language.LanguageClass 
                    });
                }
            }

            return View(Model);
        }
        /*
         * Simmilar to search query in sub contrtoller
         * Join requests with profile id and show 10 requests in alphabetical order
         */
        public ActionResult Search(string SearchQuery)
        {
            if (string.IsNullOrEmpty(SearchQuery))
            {
                ModelState.AddModelError("", "");
            }
            // Get all requests that match the title in SearchQuery
            var Requests = (from P in _ProfileRepo.GetAll()
                            where P.Requests.Count() != 0 
                            && P.Title.ToLower().Contains(SearchQuery.ToLower())
                            from R in P.Requests
                            orderby P.Title
                            select new
                            {
                                ID = R.ID,
                                Title = P.Title,
                                Year = P.Year,
                                Upvotes = R.Upvotes.Count(),
                                MovieDBID = P.MovieDBID,
                                Language = R.Language,
                                TypeID = P.TypeID
                            }).Take(10).ToList();

            PageModel<RequestViewModel> Model = new PageModel<RequestViewModel>();
            Model.Profiles = new List<RequestViewModel>();

            Model.CurrentPage = 0;
            Model.Pages = 0;
            Model.Total = 0;
            //Adds requests to list
            foreach (var R in Requests)
            {
                if (R.MovieDBID != null)
                {
                    //Gets movie DB info if TypeID is 1(movie)
                    if (R.TypeID == 1)
                    {
                        var Movie = _TMDb.GetMovie(R.MovieDBID.Value);
                        Model.Profiles.Add(new RequestViewModel {
                            ID = R.ID, 
                            Title = R.Title, 
                            Year = R.Year, 
                            Upvotes = R.Upvotes, 
                            PosterPath = Movie.PosterPath, 
                            LanguageName = R.Language.LanguageName,
                            LanguageClass = R.Language.LanguageClass
                        });
                    }
                    //Gets movie DB info if TypeID is 2(TvShow)
                    else
                    {
                        var TvShow = _TMDb.GetTvShow(R.MovieDBID.Value);
                        Model.Profiles.Add(new RequestViewModel { 
                            ID = R.ID, 
                            Title = R.Title, 
                            Year = R.Year, 
                            Upvotes = R.Upvotes, 
                            PosterPath = TvShow.PosterPath, 
                            LanguageName = R.Language.LanguageName,
                            LanguageClass = R.Language.LanguageClass
                        });
                    }
                }
                // Is there is no movie DB info then it will just have information from user
                else
                {
                    Model.Profiles.Add(new RequestViewModel { 
                        ID = R.ID, 
                        Title = R.Title, 
                        Year = R.Year, 
                        Upvotes = R.Upvotes,
                        LanguageName = R.Language.LanguageName,
                        LanguageClass = R.Language.LanguageClass
                    });
                }
            }
            
            return View("Index", Model);

        }
        public ActionResult Add()
        {
            // adds types of video(movie and tvshow)
            List<SelectListItem> types = new List<SelectListItem>();
            types.Add(new SelectListItem { Text = "Movie", Value = "1" });
            types.Add(new SelectListItem { Text = "TV-Series", Value = "2" });
            ViewBag.TypeID = types;
            
            // lists the available languages from data base
            List<Language> LanguageFromDB = (from l in _LanguageRepo.GetAll()
                                             select l).ToList();
            List<SelectListItem> Language = new List<SelectListItem>();

            foreach (Language l in LanguageFromDB)
            {
                SelectListItem NewSelectListItem = new SelectListItem
                {
                    Text = l.LanguageName,
                    Value = l.ID.ToString()
                };
                Language.Add(NewSelectListItem);
            }
            ViewBag.LanguageID = Language;

            return View(new RequestViewModel());
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(RequestViewModel Model)
        {
            if(ModelState.IsValid)
            {
                //Get subtitle profile with model.title
                var OldSubtitleProfile = GetSubtitleProfileFromTitle(Model.Title);

                // if subtitle profile exists in DB
                if(OldSubtitleProfile != null)
                {
                    //Get Subtitle with Profile ID and Language ID
                    var OldSubtitle = GetSubtitleFromSubtitleProfileIDAndLanguageID(OldSubtitleProfile.ID, Model.LanguageID);
                    // if the specific language profile exist
                    if(OldSubtitle != null)
                    {
                        //go to profile
                        return RedirectToAction("View", "Subtitle", new { id = OldSubtitle.ID });
                    }
                    //if the specific language profile does not exist

Whatsub/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Whatsub/Views/Home/Help.cshtml
@{
    ViewBag.Title = "Help";
}

<h2>FAQ</h2>

<h3>About .srt files</h3>
<p>
    Known as a SubRip subtitle file, it is a widely used and broadly compatible text file format. It is used to display subtitles
    in a video file by marking the time signatures of each segment and displaying them at the given time.
    In an .srt file, subtitles are numbered sequentally, starting at 1. The timecode format used is this:
    <b>hours:minutes:seconds, milliseconds.</b>
    A typical segment in an .srt file looks like this:
</p>
        <code id="srtexample">
            1. <br />
            00:00:03,500 --> 00:00:06,000 <br />
            Hello world! This is an example <br />
            of a SubRip subtitle file. <br />
        </code>
<br />
<p>
    Subrip files also offer a variety of ways to position and style texts with the use of coordinates and html style tags.
    The .srt file format is supported by most popular video players.
    Subrip files can be used on a personal compute by simply opening them with the video file, for example by the use of
    drag and drop. They can also be used in various other places such as Netflix and you should be able to find instructions
    on how to incorporate them quite easily.
    
</p>
<h3>Subtitle</h3>
<p>
    To find a specific subtitle just use our awesome search engine to find it. If for some reason our awesom search engin doesnt 
    find it, you can use our request page to request one.
</p>
<h3>Requests</h3>
<p>
    To issue a request for a translation, you can click the request link in the navigation bar at the top of the page.
    There you can search if a similar requests exists and if it doesnt just click the new requst link.
</p>
<p>
    Click @Html.ActionLink("here", "Index", "Request", null, null) to get to the request page.
</p>
<h3>Download a .srt file</h3>
<p>
    Start by searching for the content you want. 
    In each Subtitle page there is a download subtitle link which save the subtitle to your computer.
</p>
<h3>Upload a subtitle</h3>
<p>
    To upload a subtitle you can simply go to the subtitle page through the navigation bar and then 
    click the link "Add new subtitle".
</p>
<p>
    Click @Html.ActionLink("here", "Index", "Request", null, null) to get to the add new subtitle page.
</p>
<h3>How to translate subtitles</h3>
<p>
    Choose the film or TV show you want to translate. Select the language you want to translate into and click "Edit Subtitle". 
    Choose lines to translate from the table and translate in the translate form beneath the table. Just remember to click "Save line".
</p>
<h3>How to translate subtitles with Google Translate</h3>
    <ol>
        <li>Download the srt file of the English subtitles on the subtitle page.</li>
        <li>Save it on your computer ("Ctrl + s" will make sure the file is saved as srt. You can also write .srt after the file name in the "save as" window).</li>
        <li>Upload the srt file to <a href="http://translate.google.com/toolkit/list?hl=no#translations/active">Google Translations Tool</a> and choose what language you want the subtitles to be translated into.</li>
        <li>When you click the "Next" button you will be offered to select a translate vendor. Just click "No, thanks" if you don't want to spend your money.</li>
        <li>Choose the subtitle from the list that appears.</li>
        <li>Click "Complete" and then "OK" when it warns you that the document is only 0% complete.</li>
        <li>Click "File" and "Download".</li>
    </ol>
<p>
    Each subtitle should take under a minute to translate and upload using this method.
    The translation is not perfect but you can of course correct the Google mistakes. The task of correcting is a lot less daunting as oppose to write all down your self.
</p>
    
    

Whatsub/Views/Home/Index.cshtml
@model Whatsub.Models.IndexViewModel
@{
    ViewBag.Title = "Whatsub";
}

<!-- search hér -->
<div class="container" id="FrontPageContainer">
    <div class="row">
        <h1>WhatSub</h1>
    </div>
    <div class="row">
        <div class="col-md-12" id="indexsearch">
            <div class="SearchWrapper">
                @using (Html.BeginForm("Search", "Subtitle", FormMethod.Get, new { id = "indexsearchbar" }))
                {
                    @Html.TextBox("SearchQuery", null, new { id = "SearchInput", @class = "WantSubtitleSuggestions" })
                    <button type="submit"><span class="glyphicon glyphicon-search"></span></button>
                }
            </div>
        </div>
    </div>
    <!-- Test commit and push -->

    <div class="row" id="topandnew">
        <div class="col-md-6 col-sm-6" id="topsubtitles">
            <h2>Top Subtitles</h2>
            @if (Model.TopSubtitles != null)
            {
                <ul>
                    @foreach (var item in Model.TopSubtitles)
                    {
                        <li>
                            <a href="@Url.Action("View", "Subtitle", new { id = item.ID })">
                                @item.Title (@item.Year)
                            </a>
                        </li>
                    }
                </ul>
            }
        </div>
        <div class="col-md-6" id="newsubtitles">
            <h2>Newest Subtitles</h2>
            @if (Model.NewSubtitles != null)
            {
                <ul>
                    @foreach (var item in Model.NewSubtitles)
                    {
                        <li>
                            <a href="@Url.Action("View", "Subtitle", new { id = item.ID })">
                                @item.Title (@item.Year)
                            </a>
                        </li>
                    }
                </ul>
            }
        </div>
    </div>
</div>

Whatsub/Views/Home/SubtitleNotFound.cshtml
@{
    ViewBag.Title = "Subtitle Not Found!";
}

<h2>Sorry! Subtitle not found</h2>
<p>We're sorry, but the subtitle you're looking for doesn't seem to be in our database.</p>