Whatsub/Controllers/AjaxController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TMDbLib.Objects.General;
using Microsoft.AspNet.Identity;
using Whatsub.Models;
using System.Text.RegularExpressions;

namespace Whatsub.Controllers
{
    public class AjaxController : ParentController
    {
        /*
         * Retrieves suggestions for the dropdown
         * in search bars for Subtitles.
         */
        public JsonResult SubtitleSuggestion(string query)
        {
            var Model = new SuggestionModel<string>();

            Model.query = query;
            Model.suggestions = (from p in _ProfileRepo.GetAll()
                                 where p.Subtitles.Count() != 0
                                 && p.Title.ToLower().Contains(query.ToLower())
                                 select p.Title).ToArray();

            return Json(Model, JsonRequestBehavior.AllowGet);
        }

        /*
         * Retrieves suggestions for the dropdown
         * in search bars for Requests
         */
        public JsonResult RequestSuggestion(string query)
        {
            var Model = new SuggestionModel<string>();

            Model.query = query;
            Model.suggestions = (from p in _ProfileRepo.GetAll()
                                 where p.Requests.Count() != 0
                                 && p.Title.ToLower().Contains(query.ToLower())
                                 select p.Title).ToArray();

            return Json(Model, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult CompleteStatus(CompleteStatusViewModel Complete)
        {
            Subtitle SubtitleFound = (from s in _SubtitleRepo.GetAll()
                                      where s.ID == Complete.SubtitleID
                                      select s).SingleOrDefault();

            if (SubtitleFound != null)
            {
                //Update Subtitle
                SubtitleFound.Complete = Complete.CompleteStatus;
                _SubtitleRepo.Save();
            }
            return Json(new { Message = "Success" }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult SaveLine(EditSubtitleSaveModel Line)
        {
            Line EditLine = (from L in _LineRepo.GetAll()
                             where L.ID == Line.LineID
                             select L).SingleOrDefault();

            EditLine.Line1 = Line.Line1;
            EditLine.Line2 = Line.Line2;
            EditLine.TimeStart = TimeSpan.Parse(Line.TimeStart);
            EditLine.TimeEnd = TimeSpan.Parse(Line.TimeEnd);

            _LineRepo.Save();

            return Json(new { Message = "Success" }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult DeleteLine(EditSubtitleSaveModel Line)
        {
            // Find line to delete and delete it from DB
            Line DeleteLine = (from L in _LineRepo.GetAll()
                             where L.ID == Line.LineID
                             select L).SingleOrDefault();
            if (DeleteLine != null)
            {
                // Line found
                _LineRepo.Delete(DeleteLine);
                _LineRepo.Save();
            }
            return Json(new { Message = "Success" }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult AddLine(AddSubtitleSaveModel Line)
        {
                //Make New line
                Line NewLine = new Line()
                {
                    //ApplicationUserID = ? TODO
                    Date = DateTime.Now,
                    SubtitleID = Line.SubtitleID,
                    TimeStart = TimeSpan.Parse(Line.TimeStart),
                    TimeEnd = TimeSpan.Parse(Line.TimeEnd),
                    Line1 = Line.Line1,
                    Line2 = Line.Line2,
                };
                _LineRepo.Add(NewLine);
                _LineRepo.Save();

                return Json(new { Message = "Success" }, JsonRequestBehavior.AllowGet);


            
        }

        [HttpPost]
        public JsonResult Upvote(int? RequestID, int? UpvoteID)
        {
            Upvote Upvote;
            if (!UpvoteID.HasValue)
            {
                Upvote = new Upvote { SubtitleRequestID = RequestID.Value };
                _UpvoteRepo.Add(Upvote);
            }
            else
            {
                Upvote = (from U in _UpvoteRepo.GetAll()
                                    where U.ID == UpvoteID.Value
                                    select U).SingleOrDefault();
                _UpvoteRepo.Delete(Upvote);
            }
            _UpvoteRepo.Save();
            int count = (from U in _UpvoteRepo.GetAll()
                         where U.SubtitleRequestID == RequestID.Value
                         select U).Count();

            int ID = Upvote.ID;

            return Json(new { id = ID, Upcount = count }, JsonRequestBehavior.AllowGet);
        }
    }
}

Whatsub/Controllers/SubtitleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Whatsub.Repositories;
using Whatsub.Models;
using TMDbLib.Client;
using TMDbLib.Objects.Movies;
using TMDbLib.Objects.General;
using System.Text;
using System.IO;
using System.Text.RegularExpressions;
using Microsoft.AspNet.Identity;
using System.Globalization;


namespace Whatsub.Controllers
{
    public class SubtitleController : ParentController
    {
        public SubtitleController() : base() { }
        public SubtitleController(IRepository<SubtitleProfile> ProfileRepo, IRepository<Subtitle> SubtitleRepo = null) : base(ProfileRepo, SubtitleRepo) { }

        /* 
         * Takes care of displaying the list of SubtitleProfiles 
         * on current page
         */
        public ActionResult Index(int? Page)
        {
            // If Page has no value we have to set it to 1 to represent page 1
            if (!Page.HasValue)
            {
                Page = 1;
            }

            // Fetch all Profiles from the Database that have one or more subtitles
            var Profiles = (from x in _ProfileRepo.GetAll()
                            where x.Subtitles.Count() != 0
                            orderby x.ID descending
                            select x).Skip((Page.Value - 1) * 10).Take(10).ToList();

            PageModel<SubtitleSearchViewModel> model = new PageModel<SubtitleSearchViewModel>();
            model.Profiles = new List<SubtitleSearchViewModel>();

            // Total profiles
            model.Total = (from x in _ProfileRepo.GetAll()
                           where x.Subtitles.Count() != 0
                           select x).Count();
            // Calculate how many pages there are in total
            model.Pages = (int)Math.Ceiling((double)model.Total / 10);
            // Put the current page into the model
            model.CurrentPage = Page.Value;

            foreach (var P in Profiles)
            {
                // Check if there is an ID for The Movie DB
                if (P.MovieDBID.HasValue)
                {
                    // Current profile is a movie
                    if (P.TypeID == 1)
                    {
                        var movie = _TMDb.GetMovie(P.MovieDBID.Value);
                        model.Profiles.Add(new SubtitleSearchViewModel { ID = P.Subtitles.First().ID, Title = P.Title, Year = P.Year, PosterPath = movie.PosterPath });
                    }
                    // Current profile is a TV Show
                    else
                    {
                        var TvShow = _TMDb.GetTvShow(P.MovieDBID.Value);
                        model.Profiles.Add(new SubtitleSearchViewModel { ID = P.Subtitles.First().ID, Title = P.Title, Year = P.Year, PosterPath = TvShow.PosterPath });
                    }
                }
                else
                {
                    model.Profiles.Add(new SubtitleSearchViewModel { ID = P.Subtitles.First().ID, Title = P.Title, Year = P.Year });
                }
            }

            return View(model);
        }

        /* 
         * Takes care of subtitle search
         */
        /*
         * Search query finds 10 results that contain the word
         * And lists them on the site, finds the corresponding
         * movie poster and info
        */
        public ActionResult Search(string SearchQuery)
        {
            //Checks for empty input
            if (string.IsNullOrEmpty(SearchQuery))
            {
                ModelState.AddModelError("", "");
            }
            //Search DB for subtitle with title that contains the input
            var Profiles = (from x in _ProfileRepo.GetAll()
                            where x.Subtitles.Count() != 0 && x.Title.ToLower().Contains(SearchQuery.ToLower())
                            orderby x.Title
                            select x).Take(10).ToList();

            PageModel<SubtitleSearchViewModel> model = new PageModel<SubtitleSearchViewModel>();
            model.Profiles = new List<SubtitleSearchViewModel>();

            // Search only shows first 10
            model.CurrentPage = 0;
            model.Pages = 0;
            model.Total = 0;

            foreach (var P in Profiles)
            {
                // Check if there is an ID for The Movie DB
                if (P.MovieDBID.HasValue)
                {
                    // Current profile is a movie
                    if (P.TypeID == 1)
                    {
                        Movie movie = _TMDb.GetMovie(P.MovieDBID.Value);
                        model.Profiles.Add(new SubtitleSearchViewModel { ID = P.Subtitles.First().ID, Title = P.Title, Year = P.Year, PosterPath = movie.PosterPath });
                    }
                    // Current profile is a TV Show
                    else
                    {
                        var TvShow = _TMDb.GetTvShow(P.MovieDBID.Value);
                        model.Profiles.Add(new SubtitleSearchViewModel { ID = P.Subtitles.First().ID, Title = P.Title, Year = P.Year, PosterPath = TvShow.PosterPath });
                    }
                }
                else
                {
                    model.Profiles.Add(new SubtitleSearchViewModel { ID = P.Subtitles.First().ID, Title = P.Title, Year = P.Year });
                }

            }

            // Redirect to details page about movie if there is a single result
            if (model.Profiles.Count() == 1)
            {
                return RedirectToAction("View", new { id = model.Profiles.First().ID });
            }
            return View("Index", model);
        }

        /* 
         * Takes care of displaying the corresponding 
         * Subtitle profile page.
         * Gathers info about the page and returns it
         * to the view model.
         */
        public ActionResult View(int? id)
        {
            if (id.HasValue)
            {
                //Finds subtitle from input id and fill the ViewModel
                SubtitleProfilePageViewModel model = (from S in _SubtitleRepo.GetAll()
                                                      where S.ID == id.Value
                                                      select new SubtitleProfilePageViewModel { 
                                                                ID = S.ID,
                                                                ProfileID = S.SubtitleProfileID,
                                                                Title = S.SubtitleProfile.Title,
                                                                Year = S.SubtitleProfile.Year,
                                                                MovieDBID = S.SubtitleProfile.MovieDBID,
                                                                YoutubeUrl = S.SubtitleProfile.YouTubeURL,
                                                                Complete = S.Complete,
                                                                TypeID = S.SubtitleProfile.TypeID
                                                      }).SingleOrDefault();
                //Subtitle found
                if (model != null)
                {
                    //Get Language for subtitle
                    var Languages = (from L in _LanguageRepo.GetAll()
                                    join S in _SubtitleRepo.GetAll()
                                        on L.ID equals S.LanguageID
                                    where S.SubtitleProfileID == model.ProfileID
                                    select new
                                    {
                                        Text = L.LanguageName,
                                        Value = S.ID
                                    }).ToList();

                    //Language select list for form
                    var LanguageList = new List<SelectListItem>();
                    foreach ( var Language in Languages )
                    {
                        SelectListItem Item = new SelectListItem
                        {
                            Text = Language.Text,
                            Value = Language.Value.ToString(),
                            Selected = false
                        };

                        if (Language.Value == id.Value)
                        {
                            Item.Selected = true;
                        }

                        LanguageList.Add(Item);
                    }
                    ViewBag.Languages = LanguageList;

                    // Check if there is an ID for The Movie DB
                    if (model.MovieDBID.HasValue)
                    {
                        if (model.TypeID == 1)
                        {
                            // Get details from TheMovieDB
                            Movie movie = _TMDb.GetMovie(model.MovieDBID.Value);
                            // Populate the model object
                            model.PosterPath = movie.PosterPath;
                            model.Overview = movie.Overview;
                        }
                        else
                        {
                            //Get details from TheMovieDB
                            var TvShow = _TMDb.GetTvShow(model.MovieDBID.Value);
                            //Populate the model object
                            model.PosterPath = TvShow.PosterPath;
                            model.Overview = TvShow.Overview;
                        }
                    }

                    return View(model); // Success
                }
                else
                {
                    return View("SubtitleNotFound"); // ID not found
                }
            }

            return View("Error"); // No ID
        }


        /* 
         * Takes care of displaying the edit page for each
         * language. Receives info about the pagenumber and returns

Whatsub/Views/Subtitle/Add.cshtml
@using Microsoft.AspNet.Identity;
@using Microsoft.AspNet.Identity.EntityFramework;
@using Whatsub.Models;
@model Whatsub.Models.AddSubtitleViewModel
@{
    ViewBag.Title = "Add";
}

<h2>Add subtitle page</h2>
<span id="ErrorInputMessage"><span class="glyphicon glyphicon-remove form-control-feedback"></span>Input Error!</span>
    @using (Html.BeginForm("Create", "Subtitle", FormMethod.Post, new
    {
        enctype = "multipart/form-data",
        id = "AddNewSubtitleForm",
        name = "AddNewSubtitleForm"
    }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true);

            <fieldset>
                <div class="row form-group">
                    @Html.LabelFor(m => m.Title, new { @class = "col-md-2 AddSubLeftCol control-label" })
                    <div class="col-md-4">
                        @Html.TextBoxFor(m => m.Title, new { @class = "form-control" })
                    </div>
                </div>
                <div class="row form-group">
                    @Html.LabelFor(m => m.TypeID, "Select Type", new { @class = "col-md-2 AddSubLeftCol control-label" })
                    <div class="col-md-4">
                        @Html.DropDownList("TypeID", null, new { @class = "form-control" })
                    </div>
                </div>
                <div class="row form-group">
                    @Html.LabelFor(m => m.Year, "Year", new { @class = "col-md-2 AddSubLeftCol control-label" })
                    <div class="col-md-4">
                        @Html.TextBoxFor(m => m.Year, null, new { @class = "form-control" })
                    </div>
                </div>
                <div class="row form-group">
                    @Html.LabelFor(m => m.LanguageID, "Subtitle Language", new { @class = "col-md-2 AddSubLeftCol control-label" })
                    <div class="col-md-4">
                        @Html.DropDownList("LanguageID", null, new { @class = "form-control" })
                    </div>
                </div>
            </fieldset>
            <h3 id="UploadSrtFile">Upload .srt file and/or link to video trailer (Optional)</h3>
            <div class="row">
                <div class="col-md-4" id="UploadFile">
                    <input id="SrtUpload" name="SrtUpload" type="file"/>
                    @Html.ValidationMessageFor(m => m.SrtUpload)
                </div>
            </div>
            <div class="row form-group">
                @Html.LabelFor(m => m.VideoUrl, "Link to trailer", new { @class = "col-md-2 AddSubLeftCol control-label" })
                <div class="col-md-4">
                    @Html.TextBoxFor(m => m.VideoUrl, new { @class = "form-control" })
                </div>
            </div>
        
            
            <div class="row" id="SubmitContent">
                <div class="col-md-2">
                </div>
                <div class="col-md-4">
                    <input type="submit" name="operation" id="process" value="Create" class="btn btn-primary col-md-2">
                </div>
                
            </div>
 
    }

<div id="UploadProcessingBox">
    <p>Uploading, Please wait...</p>
    <img src="@Url.Content("~/Content/Images/ajax-loader.gif")" alt="..."/>
</div>

Whatsub/Views/Subtitle/AddSubtitleError.cshtml
@{
    ViewBag.Title = "AddSubtitleError";
}

<h2>Oops there seems to be a problem with the subtitle you're trying to add please try again....</h2>

<p>The problem might be one of the following:</p>
<ul>
    <li>You are not logged in</li>
    <li>The form was not correctly filled out</li>
    <li>The content of the .srt file is not compliant to the standard</li>
</ul>

Whatsub/Views/Subtitle/Edit.cshtml
@using Microsoft.AspNet.Identity;
@using Microsoft.AspNet.Identity.EntityFramework;
@using Whatsub.Models;
@model Whatsub.Models.EditSubtitlePageViewModel
@{
    ViewBag.Title = "Edit " + Model.Title;
}

<div class="container">
    <div class="row">
        <div class="col-md-12 PageHeader">
            <h2>@Model.Title (@Model.Year)</h2>
            <a href="@Url.Action("View", "Subtitle", new { id = Model.SubtitleID })">
                <span class="glyphicon glyphicon-chevron-left"></span>
                <span class="Text">Back to profile</span>
            </a>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8">
            @Html.DropDownList("CompleteStatus", null, new { id = "CompleteStatus"})
            <span id="CompleteChanged"><span class="glyphicon glyphicon-ok form-control-feedback"></span>Status has been changed</span>
        </div>
        <div class="col-md-8">
            Language: @Model.SubtitleLanguage
        </div>
    
    </div>
    @Html.Partial("EditTablePartial")
    <div class="row">
        <div class="col-md-6">
            @if (Model.PageNumber - 1 > 0)
            {
                @Html.ActionLink("Prev", "Edit", new { PageNumber = (Model.PageNumber - 1) }, new { id = "EditPagePrev" })
            }
            <span id="EditPageNbr">Page Number: @Model.PageNumber</span>
            @if (Model.PageNumber + 1 <= Model.Pages)
            {
                @Html.ActionLink("Next", "Edit", new { PageNumber = (Model.PageNumber + 1) }, new { id = "EditPageNext" })
            }
        </div>
    </div>  
    <div class="row">
        <span id="ErrorInputMessage"><span class="glyphicon glyphicon-remove form-control-feedback"></span>Input Error!</span>
        @using (Html.BeginForm("SaveLine", "Ajax", FormMethod.Get, new { id = "EditForm" }))
        {
            <div class="row">
                <div class="col-md-12">
                    @Html.Hidden("PageNumber", Model.PageNumber)
                    @Html.Hidden("LineID")
                    @Html.Hidden("SubtitleID", Model.SubtitleID)
                    @Html.Hidden("LineNr")
                    <div class="form-group">
                        @Html.TextBox("TimeStart", null, new { @class="form-control"})
                    </div>
                    
                    <span>--></span>
                    <div class="form-group">
                        @Html.TextBox("TimeEnd", null, new { @class = "form-control" }) Time segment
                    </div>
                </div>
            </div>
            <div class="row LineInput">
                <div class="col-md-12">
                    <div class="form-group">
                        @Html.TextBox("Line1", null, new { @class = "form-control" }) Line 1
                    </div>
                </div>
            </div>
            <div class="row LineInput">
                <div class="col-md-12">
                    <div class="form-group">
                        @Html.TextBox("Line2", null, new { @class = "form-control" }) Line 2
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <a class="btn btn-primary" id="btnSave">Update line</a>
                    <a class="btn btn-primary" id="btnAdd">Add New line</a>
                    <a class="btn btn-primary" id="btnDelete">Delete line</a>
                </div>
            </div>
        }
    </div>
    <div class="row">
        <div class="col-md-4" id="SubPageRightCol">
            <div class="row">
                @{
                    if (Request.IsAuthenticated)
                    {
                        var CurrentUser = User.Identity.GetUserName();
                        <h3>
                            @CurrentUser
                        </h3>
                    }
                }

            </div>
            @{
                if (Request.IsAuthenticated)
                {
                    <div class="row">
                        @using (Html.BeginForm("AddComment", "Subtitle", FormMethod.Post, new { id = "CommentForm" }))
                        {
                            <fieldset>
                                <div class="form-horizontal">
                                    <label class="sr-only" for="CommentText">Comment</label>
                                    <textarea class="form-control" rows="3" id="CommentText" style="max-width: 600px;" name="CommentText" placeholder="Share your thoughts"></textarea>
                                    <button type="submit" class="btn btn-primary" id="SubPageCommentButton">Send</button>
                                </div>
                            </fieldset>
                        }
                    </div>
                }
            }
            <div class="row">
                <h3>Newest Comments</h3>
            </div>
            <div class="row">
                <ul class="list-group" style="max-width: 600px;" data-id="@Model.ID">
                    <div id="CommentIn">
                        <div id="CommentList">
                        </div>
                    </div>
                </ul>
            </div>
        </div>
        </div>
</div>

<script type="text/html" id="CommentTemplate">

    <li class="list-group-item">
        <p>
            <span class="glyphicon glyphicon-user"></span>
            <span class="text-primary" data-content="Username"></span><!-- Username-->
            <span class="text-muted" data-content="CommentDate"></span><!-- Date-->
        </p>
        <p>
            <span data-content="CommentText"></span> <!-- Comment text-->
        </p>
    </li>
</script>

Whatsub/Views/Subtitle/EditTablePartial.cshtml
@using Microsoft.AspNet.Identity;
@using Microsoft.AspNet.Identity.EntityFramework;
@using Whatsub.Models;
@model Whatsub.Models.EditSubtitlePageViewModel

<div class="row" id="EditPageTable">
    <div class="col-md-6" id="EditTableCol">
        <table style="width:100%;" id="EditTable">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Start</th>
                    <th>End</th>
                    <th>Text</th>
                </tr>
            </thead>
            @for (int i = 0; i < Model.Lines.Count(); ++i)
            {
                <tbody class="SubtitleLine" id="@Model.Lines[i].ID">
                    <tr>
                        <td rowspan="2" class="LineNr">
                            @( (Model.PageNumber - 1) * 10 + i + 1)
                            <input type="hidden" class="LineID" value="@Model.Lines[i].ID" />
                        </td>
                        <td rowspan="2" class="TimeStart">@Model.Lines[i].TimeStart.ToString()</td>
                        <td rowspan="2" class="TimeEnd">@Model.Lines[i].TimeEnd.ToString()</td>
                        <td class="Line1">@Model.Lines[i].Line1</td>
                    </tr>
                    <tr>
                        <td class="Line2">@Model.Lines[i].Line2</td>
                    </tr>
                </tbody>
            }
        </table>
        
    </div>  
</div>

Whatsub/Views/Subtitle/Index.cshtml
@model Whatsub.Models.PageModel<Whatsub.Models.SubtitleSearchViewModel>

@{
    ViewBag.Title = "Index";
}

<h2>Subtitles</h2>

<section class="main">
    <div class="container SubPageList">
        <div class="row">
            <div class="col-md-12">
                @using (Html.BeginForm("Search", "Subtitle", FormMethod.Get))
                {
                    @Html.ValidationSummary()
                    <div class="SearchWrapper">
                        @Html.TextBox("SearchQuery", null, new { @class = "WantSubtitleSuggestions" })
                        <button type="submit"><span class="glyphicon glyphicon-search"></span></button>
                        @Html.ActionLink("Search requests", "Index", "Request", null, new { @class = "SubPageActionLinks" })
                        @if(Request.IsAuthenticated)
                        {  
                            @Html.ActionLink("Add new subtitle", "Add", "Subtitle", null, new { @class = "SubPageActionLinks" })
                        }
                    </div>
                }
            </div>
        </div>
        @foreach (var Profile in Model.Profiles)
        {
            <div class="row ListPageRow">
                <div class="col-md-12 SubPageColumn BiggerFont">
                    <a href="@Url.Action("View","Subtitle", new {id = Profile.ID})">
                        @{
                            if (@Profile.PosterPath != null)
                            {
                                <img src="@Url.Content("http://image.tmdb.org/t/p/w92" + Profile.PosterPath)" alt="@Profile.Title (@Profile.Year)" class="SubPagePoster" height="100" />
                            }
                            else
                            {
                                <img src="@Url.Content("~/Content/Images/NoPosterSmall.jpg")" alt="@Profile.Title (@Profile.Year)" class="SubPagePoster" height="100" />
                            }
                        }
                        <span> @Profile.Title (@Profile.Year)</span>
                    </a>
                </div>
            </div>
        }
    </div>
    <div class="LinkToRequests" id="LinkToRequests">
        @if (Model.Profiles.Count() == 0)
        {
            <p>
                Not finding the subtitle you are looking for? Click @Html.ActionLink("here", "Index", "Request") here to see if there is a request for this subtitle
            </p>
        }
    </div>
    <span class="CurrPage">
        @if (Model.CurrentPage - 1 > 0)
        {
            @Html.ActionLink("Prev", "Index", new { Page = (Model.CurrentPage - 1) })
        }
        @for (int i = 1; i <= Model.Pages; ++i)
        {
            if (!(Model.CurrentPage == i))
            {
                @Html.ActionLink(i.ToString(), "Index", new { Page = i }, new { @class = "Pages" });
            }
            else
            {
                @Html.AttributeEncode(i)
            }
        }
        @if (Model.CurrentPage + 1 <= Model.Pages)
        {
            @Html.ActionLink("Next", "Index", new { Page = (Model.CurrentPage + 1) })
        }
    </span>
</section>

Whatsub/Views/Subtitle/SubtitleNotFound.cshtml
@{
    ViewBag.Title = "Subtitle Not Found!";
}

<h2>Sorry! Subtitle not found</h2>
<p>We're sorry, but the subtitle you're looking for doesn't seem to be in our database.</p>